name: ses_sion_1_7
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^5.0.2
  intl: ^0.17.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  extended_masked_text: ^2.3.1
  cupertino_icons: ^1.0.2
  pinput: ^3.0.1
  http: ^1.2.0
  image_picker: ^1.0.7
  url_launcher: ^6.1.11
  supabase_flutter: ^2.3.1
  crypto: ^3.0.3
#  flutter_native_splash: ^2.3.13


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/img.png"
  android_12:
    color: "#FFFFFF"
    image: "assets/img.png"
    branding: "assets/img_1.png"


flutter:

  uses-material-design: true

  assets:
    - assets/

